version: '3'
  
services:
  walkabout:
    image: walkabout
    environment:
      - FLASKLOGIN_MONGO_HOST=mongo
      - FLASKLOGIN_MONGO_PORT=27017
      - FLASKLOGIN_MONGO_DBNAME=walkabout

      - ROOMS_MONGO_HOST=mongo
      - ROOMS_MONGO_PORT=27017
      - ROOMS_MONGO_DBNAME=walkabout

      - ROOMS_NODE_HOSTNAME=localhost:5000
      - ROOMS_NODE_NAME=local
      - ROOMS_NODE_HOST=0.0.0.0
      - ROOMS_NODE_PORT=5000
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - mongo
    volumes:
      - "${PWD}/server.py:/app/server.py:ro"
      - "${PWD}/../../src/:/rooms/src/"

  mongo:
    image: mongo
    volumes:
      - ./.data/mongodb:/data/db
