def kickoff(npc):
    npc.move_to(450,1100)
    npc.sleep(4)
    npc.say("They're just doing their job Dear")
    npc.sleep(8)
    npc.say("That's a terrible thing to say.")
    npc.sleep(8)
    npc.say("No, but you could show more respect to your dear father")
    npc.sleep(8)
    npc.say("They never change do they")
    npc.sleep(4)